all:
  hosts:
    tollgate-vps:
      ansible_host: "{{ vps_ip }}"
      ansible_user: root
  children:
    voting_servers:
      hosts:
        tollgate-vps:
    mint_hosts:
      hosts:
        tollgate-vps:
