export const IMPLEMENTATION_KIND_QUESTIONNAIRE_DEFINITION = 14120;
export const IMPLEMENTATION_KIND_QUESTIONNAIRE_STATE = 14121;
export const IMPLEMENTATION_KIND_QUESTIONNAIRE_RESPONSE_PRIVATE = 14122;
export const IMPLEMENTATION_KIND_QUESTIONNAIRE_RESULT_SUMMARY = 14123;
export const IMPLEMENTATION_KIND_QUESTIONNAIRE_RESPONSE_BLIND = 14124;

export const SPEC_KIND_QUESTIONNAIRE_DEFINITION = 34500;
export const SPEC_KIND_QUESTIONNAIRE_STATE = 34501;
export const SPEC_KIND_QUESTIONNAIRE_RESPONSE_BLIND = 34502;
export const SPEC_KIND_QUESTIONNAIRE_RESULT_SUMMARY = 34503;

export const QUESTIONNAIRE_BLIND_TOKEN_MESSAGE_DOMAIN = "auditable-voting/questionnaire-blind-token/v1";
export const QUESTIONNAIRE_NULLIFIER_DOMAIN = "auditable-voting/questionnaire-nullifier/v1";
export const QUESTIONNAIRE_RESULT_HASH_DOMAIN = "auditable-voting/questionnaire-result-hash/v1";

export const QUESTIONNAIRE_RESPONSE_MODE_BLIND_TOKEN = "blind_token";
export const QUESTIONNAIRE_RESPONSE_MODE_LEGACY_PRIVATE_ENVELOPE = "legacy_private_envelope";

export type QuestionnaireResponseMode =
  | typeof QUESTIONNAIRE_RESPONSE_MODE_BLIND_TOKEN
  | typeof QUESTIONNAIRE_RESPONSE_MODE_LEGACY_PRIVATE_ENVELOPE;
