export const IMPLEMENTATION_KIND_QUESTIONNAIRE_DEFINITION = 14120;
export const IMPLEMENTATION_KIND_QUESTIONNAIRE_STATE = 14121;
export const IMPLEMENTATION_KIND_QUESTIONNAIRE_RESPONSE_PRIVATE = 14122;
export const IMPLEMENTATION_KIND_QUESTIONNAIRE_RESULT_SUMMARY = 14123;
export const IMPLEMENTATION_KIND_QUESTIONNAIRE_RESPONSE_BLIND = 14124;
export const IMPLEMENTATION_KIND_QUESTIONNAIRE_SUBMISSION_DECISION = 14125;

export const SPEC_KIND_QUESTIONNAIRE_DEFINITION = 34500;
export const SPEC_KIND_QUESTIONNAIRE_STATE = 34501;
export const SPEC_KIND_QUESTIONNAIRE_RESPONSE_BLIND = 34502;
export const SPEC_KIND_QUESTIONNAIRE_RESULT_SUMMARY = 34503;
export const SPEC_KIND_QUESTIONNAIRE_SUBMISSION_DECISION = 34504;

export const QUESTIONNAIRE_BLIND_TOKEN_MESSAGE_DOMAIN = "auditable-voting/questionnaire-blind-token/v1";
export const QUESTIONNAIRE_NULLIFIER_DOMAIN = "auditable-voting/questionnaire-nullifier/v1";
export const QUESTIONNAIRE_RESULT_HASH_DOMAIN = "auditable-voting/questionnaire-result-hash/v1";

export const QUESTIONNAIRE_RESPONSE_MODE_BLIND_TOKEN = "blind_token";
export const QUESTIONNAIRE_RESPONSE_MODE_LEGACY_PRIVATE_ENVELOPE = "legacy_private_envelope";
export const QUESTIONNAIRE_PROTOCOL_VERSION_V1 = 1;
export const QUESTIONNAIRE_PROTOCOL_VERSION_V2 = 2;
export const QUESTIONNAIRE_FLOW_MODE_LEGACY_PRIVATE_DM = "legacy_private_dm";
export const QUESTIONNAIRE_FLOW_MODE_PUBLIC_SUBMISSION_V1 = "public_submission_v1";

export type QuestionnaireResponseMode =
  | typeof QUESTIONNAIRE_RESPONSE_MODE_BLIND_TOKEN
  | typeof QUESTIONNAIRE_RESPONSE_MODE_LEGACY_PRIVATE_ENVELOPE;

export type QuestionnaireFlowMode =
  | typeof QUESTIONNAIRE_FLOW_MODE_LEGACY_PRIVATE_DM
  | typeof QUESTIONNAIRE_FLOW_MODE_PUBLIC_SUBMISSION_V1;
